spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpa_audit?createDatabaseIfNotExist=true
    username: root
    password: kybe3buoi
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
